insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 1);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 2);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 3);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 4);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 5);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 6);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 7);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 8);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 9);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 10);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 11);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 12);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 13);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 14);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 15);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 16);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 17);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 18);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 19);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 20);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 21);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 22);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 23);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 24);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 25);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 26);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 27);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 28);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 29);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 30);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 31);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 32);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 33);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 34);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 35);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 36);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 37);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 38);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 39);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 40);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 41);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 42);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 43);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 44);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 45);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 46);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 47);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 48);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 49);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 50);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 51);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 52);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 53);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 54);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 55);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 56);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 57);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 58);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 59);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 60);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 61);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 62);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 63);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 64);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 65);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 66);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 67);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 68);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 69);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 70);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 71);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 72);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 73);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 74);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 75);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 76);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 77);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 78);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 79);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 80);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 81);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 82);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 83);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 84);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 85);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 86);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 87);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 88);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 89);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 90);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 91);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 92);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 93);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 94);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 95);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 96);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 97);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 98);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 99);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 100);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 101);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 102);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 103);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 104);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 105);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 106);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 107);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 108);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 109);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 110);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 111);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 112);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 113);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 114);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 115);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 116);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 117);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 118);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 119);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 120);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 121);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 122);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 123);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 124);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 125);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 126);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 127);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 128);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 129);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 130);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 131);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 132);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 133);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 134);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 135);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 136);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 137);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 138);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 139);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 140);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 141);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 142);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 143);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 144);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 145);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 146);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 147);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 148);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 149);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 150);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 151);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 152);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 153);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 154);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 155);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 156);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 157);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 158);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 159);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 160);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 161);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 162);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 163);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 164);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 165);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 166);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 167);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 168);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 169);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 170);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 171);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 172);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 173);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 174);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 175);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 176);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 177);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 178);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 179);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 180);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 181);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 182);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 183);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 184);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 185);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 186);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 187);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 188);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 189);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 190);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 191);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 192);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 193);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 194);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 195);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 196);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 197);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 198);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 199);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 200);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 201);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 202);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 203);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 204);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 205);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 206);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 207);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 208);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 209);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 210);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 211);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 212);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 213);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 214);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 215);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 216);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 217);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 218);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 219);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 220);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 221);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 222);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 223);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 224);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 225);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 226);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 227);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 228);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 229);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 230);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 231);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 232);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 233);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 234);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 235);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 236);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 237);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 238);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 239);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 240);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 241);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 242);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 243);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 244);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 245);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 246);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 247);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 248);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 249);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 250);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 251);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 252);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 253);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 254);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 255);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 256);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 257);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 258);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 259);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 260);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 261);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 262);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 263);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 264);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 265);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 266);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 267);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 268);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 269);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 270);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 271);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 272);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 273);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 274);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 275);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 276);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 277);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 278);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 279);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 280);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 281);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 282);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 283);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 284);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 285);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 286);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 287);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 288);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 289);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 290);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 291);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 292);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 293);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 294);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 295);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 296);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 297);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 298);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 299);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 300);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 301);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 302);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 303);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 304);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 305);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 306);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 307);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 308);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 309);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 310);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 311);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 312);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 313);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 314);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 315);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 316);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 317);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 318);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 319);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 320);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 321);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 322);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 323);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 324);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 325);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 326);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 327);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 328);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 329);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 330);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 331);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 332);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 333);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 334);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 335);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 336);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 337);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 338);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 339);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 340);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 341);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 342);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 343);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 344);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 345);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 346);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 347);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 348);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 349);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 350);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 351);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 352);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 353);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 354);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 355);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 356);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 357);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 358);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 359);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 360);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 361);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 362);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 363);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 364);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 365);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 366);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 367);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 368);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 369);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 370);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 371);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 372);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 373);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 374);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 375);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 376);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 377);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 378);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 379);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 380);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 381);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 382);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 383);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 384);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 385);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 386);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 387);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 388);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 389);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 390);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 391);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 392);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 393);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 394);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 395);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 396);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 397);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 398);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 399);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 400);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 401);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 402);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 403);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 404);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 405);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 406);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 407);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 408);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 409);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 410);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 411);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 412);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 413);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 414);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 415);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 416);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 417);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 418);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 419);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 420);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 421);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 422);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 423);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 424);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 425);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 426);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 427);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 428);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 429);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 430);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 431);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 432);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 433);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 434);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 435);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 436);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 437);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 438);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 439);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 440);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 441);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 442);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 443);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 444);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 445);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 446);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 447);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 448);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 449);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 450);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 451);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 452);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 453);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 454);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 455);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 456);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 457);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 458);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 459);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 460);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 461);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 462);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 463);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 464);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 465);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 466);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 467);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 468);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 469);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 470);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 471);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 472);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 473);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 474);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 475);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 476);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 477);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 478);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 479);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 480);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 481);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 482);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 483);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 484);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 485);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 486);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 487);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 488);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 489);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 490);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 491);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 492);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 493);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 494);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 495);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 496);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 497);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 498);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 499);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 500);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 501);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 502);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 503);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 504);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 505);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 506);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 507);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 508);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 509);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 510);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 511);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 512);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 513);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 514);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 515);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 516);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 517);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 518);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 519);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 520);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 521);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 522);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 523);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 524);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 525);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 526);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 527);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 528);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 529);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 530);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 531);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 532);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 533);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 534);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 535);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 536);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 537);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 538);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 539);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 540);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 541);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 542);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 543);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 544);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 545);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 546);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 547);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 548);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 549);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 550);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 551);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 552);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 553);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 554);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 555);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 556);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 557);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 558);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 559);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 560);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 561);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 562);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 563);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 564);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 565);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 566);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 567);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 568);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 569);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 570);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 571);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 572);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 573);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 574);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 575);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 576);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 577);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 578);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 579);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 580);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 581);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 582);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 583);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 584);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 585);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 586);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 587);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 588);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 589);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 590);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 591);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 592);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 593);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 594);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 595);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 596);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 597);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 598);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 599);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 600);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 601);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 602);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 603);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 604);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 605);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 606);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 607);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 608);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 609);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 610);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 611);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 612);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 613);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 614);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 615);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 616);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 617);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 618);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 619);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 620);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 621);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 622);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 623);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 624);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 625);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 626);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 627);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 628);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 629);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 630);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 631);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 632);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 633);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 634);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 635);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 636);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 637);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 638);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 639);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 640);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 641);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 642);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 643);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 644);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 645);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 646);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 647);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 648);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 649);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 650);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 651);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 652);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 653);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 654);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 655);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 656);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 657);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 658);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 659);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 660);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 661);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 662);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 663);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 664);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 665);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 666);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 667);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 668);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 669);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 670);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 671);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 672);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 673);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 674);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 675);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 676);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 677);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 678);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 679);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 680);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 681);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 682);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 683);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 684);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 685);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 686);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 687);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 688);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 689);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 690);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 691);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 692);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 693);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 694);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 695);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 696);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 697);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 698);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 699);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 700);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 701);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 702);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 703);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 704);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 705);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 706);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 707);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 708);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 709);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 710);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 711);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 712);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 713);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 714);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 715);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 716);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 717);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 718);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 719);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 720);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 721);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 722);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 723);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 724);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 725);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 726);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 727);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 728);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 729);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 730);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 731);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 732);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 733);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 734);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 735);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 736);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 737);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 738);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 739);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 740);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 741);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 742);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 743);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 744);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 745);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 746);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 747);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 748);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 749);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 750);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 751);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 752);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 753);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 754);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 755);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 756);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 757);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 758);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 759);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 760);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 761);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 762);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 763);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 764);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 765);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 766);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 767);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 768);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 769);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 770);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 771);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 772);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 773);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 774);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 775);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 776);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 777);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 778);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 779);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 780);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 781);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 782);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 783);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 784);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 785);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 786);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 787);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 788);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 789);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 790);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 791);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 792);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 793);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 794);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 795);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 796);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 797);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 798);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 799);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 800);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 801);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 802);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 803);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 804);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 805);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 806);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 807);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 808);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 809);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 810);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 811);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 812);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 813);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 814);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 815);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 816);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 817);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 818);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 819);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 820);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 821);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 822);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 823);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 824);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 825);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 826);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 827);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 828);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 829);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 830);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 831);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 832);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 833);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 834);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 835);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 836);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 837);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 838);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 839);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 840);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 841);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 842);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 843);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 844);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 845);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 846);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 847);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 848);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 849);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 850);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 851);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 852);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 853);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 854);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 855);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 856);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 857);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 858);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 859);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 860);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 861);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 862);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 863);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 864);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 865);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 866);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 867);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 868);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 869);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 870);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 871);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 872);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 873);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 874);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 875);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 876);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 877);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 878);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 879);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 880);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 881);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 882);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 883);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 884);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 885);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 886);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 887);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 888);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 889);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 890);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 891);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 892);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 893);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 894);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 895);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 896);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 897);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 898);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 899);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 900);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 901);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 902);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 903);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 904);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 905);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 906);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 907);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 908);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 909);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 910);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 911);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 912);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 913);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 914);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 915);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 916);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 917);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 918);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 919);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 920);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 921);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 922);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 923);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 924);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 925);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 926);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 927);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 928);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 929);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 930);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 931);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 932);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 933);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 934);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 935);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 936);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 937);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 938);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 939);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 940);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 941);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 942);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 943);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 944);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 945);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 946);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 947);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 948);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 949);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 950);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 951);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 952);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 953);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 954);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 955);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 956);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 957);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 958);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 959);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 960);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 961);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 962);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 963);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 964);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 965);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 966);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 967);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 968);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 969);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 970);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 971);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 972);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 973);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 974);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 975);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 976);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 977);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 978);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 979);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 980);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 981);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 982);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 983);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 984);
insert into person_hobby (hobbies_name, persons_id) values ('mushroom hunting', 985);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 986);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 987);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 988);
insert into person_hobby (hobbies_name, persons_id) values ('sand art', 989);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 990);
insert into person_hobby (hobbies_name, persons_id) values ('water sports', 991);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 992);
insert into person_hobby (hobbies_name, persons_id) values ('horseback riding', 993);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 994);
insert into person_hobby (hobbies_name, persons_id) values ('hunting', 995);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 996);
insert into person_hobby (hobbies_name, persons_id) values ('photography', 997);
insert into person_hobby (hobbies_name, persons_id) values ('rowing', 998);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 999);
insert into person_hobby (hobbies_name, persons_id) values ('geocaching', 1000);
