insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 1);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 2);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 3);
insert into person_hobby (hobbies_name, persons_id) values ('running', 4);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 5);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 6);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 7);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 8);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 9);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 10);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 11);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 12);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 13);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 14);
insert into person_hobby (hobbies_name, persons_id) values ('running', 15);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 16);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 17);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 18);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 19);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 20);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 21);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 22);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 23);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 24);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 25);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 26);
insert into person_hobby (hobbies_name, persons_id) values ('running', 27);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 28);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 29);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 30);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 31);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 32);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 33);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 34);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 35);
insert into person_hobby (hobbies_name, persons_id) values ('running', 36);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 37);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 38);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 39);
insert into person_hobby (hobbies_name, persons_id) values ('running', 40);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 41);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 42);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 43);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 44);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 45);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 46);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 47);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 48);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 49);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 50);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 51);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 52);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 53);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 54);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 55);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 56);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 57);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 58);
insert into person_hobby (hobbies_name, persons_id) values ('running', 59);
insert into person_hobby (hobbies_name, persons_id) values ('running', 60);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 61);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 62);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 63);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 64);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 65);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 66);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 67);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 68);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 69);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 70);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 71);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 72);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 73);
insert into person_hobby (hobbies_name, persons_id) values ('running', 74);
insert into person_hobby (hobbies_name, persons_id) values ('running', 75);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 76);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 77);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 78);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 79);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 80);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 81);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 82);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 83);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 84);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 85);
insert into person_hobby (hobbies_name, persons_id) values ('running', 86);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 87);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 88);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 89);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 90);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 91);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 92);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 93);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 94);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 95);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 96);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 97);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 98);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 99);
insert into person_hobby (hobbies_name, persons_id) values ('running', 100);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 101);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 102);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 103);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 104);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 105);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 106);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 107);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 108);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 109);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 110);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 111);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 112);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 113);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 114);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 115);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 116);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 117);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 118);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 119);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 120);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 121);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 122);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 123);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 124);
insert into person_hobby (hobbies_name, persons_id) values ('running', 125);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 126);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 127);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 128);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 129);
insert into person_hobby (hobbies_name, persons_id) values ('running', 130);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 131);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 132);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 133);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 134);
insert into person_hobby (hobbies_name, persons_id) values ('running', 135);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 136);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 137);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 138);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 139);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 140);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 141);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 142);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 143);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 144);
insert into person_hobby (hobbies_name, persons_id) values ('running', 145);
insert into person_hobby (hobbies_name, persons_id) values ('running', 146);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 147);
insert into person_hobby (hobbies_name, persons_id) values ('running', 148);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 149);
insert into person_hobby (hobbies_name, persons_id) values ('running', 150);
insert into person_hobby (hobbies_name, persons_id) values ('running', 151);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 152);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 153);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 154);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 155);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 156);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 157);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 158);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 159);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 160);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 161);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 162);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 163);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 164);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 165);
insert into person_hobby (hobbies_name, persons_id) values ('running', 166);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 167);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 168);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 169);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 170);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 171);
insert into person_hobby (hobbies_name, persons_id) values ('running', 172);
insert into person_hobby (hobbies_name, persons_id) values ('running', 173);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 174);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 175);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 176);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 177);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 178);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 179);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 180);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 181);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 182);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 183);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 184);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 185);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 186);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 187);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 188);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 189);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 190);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 191);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 192);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 193);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 194);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 195);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 196);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 197);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 198);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 199);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 200);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 201);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 202);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 203);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 204);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 205);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 206);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 207);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 208);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 209);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 210);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 211);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 212);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 213);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 214);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 215);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 216);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 217);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 218);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 219);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 220);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 221);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 222);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 223);
insert into person_hobby (hobbies_name, persons_id) values ('running', 224);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 225);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 226);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 227);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 228);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 229);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 230);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 231);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 232);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 233);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 234);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 235);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 236);
insert into person_hobby (hobbies_name, persons_id) values ('running', 237);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 238);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 239);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 240);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 241);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 242);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 243);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 244);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 245);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 246);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 247);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 248);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 249);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 250);
insert into person_hobby (hobbies_name, persons_id) values ('running', 251);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 252);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 253);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 254);
insert into person_hobby (hobbies_name, persons_id) values ('running', 255);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 256);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 257);
insert into person_hobby (hobbies_name, persons_id) values ('running', 258);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 259);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 260);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 261);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 262);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 263);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 264);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 265);
insert into person_hobby (hobbies_name, persons_id) values ('running', 266);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 267);
insert into person_hobby (hobbies_name, persons_id) values ('running', 268);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 269);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 270);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 271);
insert into person_hobby (hobbies_name, persons_id) values ('running', 272);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 273);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 274);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 275);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 276);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 277);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 278);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 279);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 280);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 281);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 282);
insert into person_hobby (hobbies_name, persons_id) values ('running', 283);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 284);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 285);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 286);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 287);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 288);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 289);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 290);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 291);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 292);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 293);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 294);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 295);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 296);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 297);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 298);
insert into person_hobby (hobbies_name, persons_id) values ('running', 299);
insert into person_hobby (hobbies_name, persons_id) values ('running', 300);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 301);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 302);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 303);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 304);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 305);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 306);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 307);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 308);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 309);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 310);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 311);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 312);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 313);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 314);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 315);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 316);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 317);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 318);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 319);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 320);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 321);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 322);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 323);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 324);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 325);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 326);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 327);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 328);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 329);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 330);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 331);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 332);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 333);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 334);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 335);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 336);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 337);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 338);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 339);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 340);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 341);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 342);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 343);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 344);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 345);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 346);
insert into person_hobby (hobbies_name, persons_id) values ('running', 347);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 348);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 349);
insert into person_hobby (hobbies_name, persons_id) values ('running', 350);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 351);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 352);
insert into person_hobby (hobbies_name, persons_id) values ('running', 353);
insert into person_hobby (hobbies_name, persons_id) values ('running', 354);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 355);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 356);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 357);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 358);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 359);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 360);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 361);
insert into person_hobby (hobbies_name, persons_id) values ('running', 362);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 363);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 364);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 365);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 366);
insert into person_hobby (hobbies_name, persons_id) values ('running', 367);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 368);
insert into person_hobby (hobbies_name, persons_id) values ('running', 369);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 370);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 371);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 372);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 373);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 374);
insert into person_hobby (hobbies_name, persons_id) values ('running', 375);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 376);
insert into person_hobby (hobbies_name, persons_id) values ('running', 377);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 378);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 379);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 380);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 381);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 382);
insert into person_hobby (hobbies_name, persons_id) values ('running', 383);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 384);
insert into person_hobby (hobbies_name, persons_id) values ('running', 385);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 386);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 387);
insert into person_hobby (hobbies_name, persons_id) values ('running', 388);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 389);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 390);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 391);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 392);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 393);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 394);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 395);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 396);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 397);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 398);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 399);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 400);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 401);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 402);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 403);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 404);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 405);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 406);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 407);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 408);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 409);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 410);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 411);
insert into person_hobby (hobbies_name, persons_id) values ('running', 412);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 413);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 414);
insert into person_hobby (hobbies_name, persons_id) values ('running', 415);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 416);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 417);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 418);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 419);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 420);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 421);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 422);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 423);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 424);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 425);
insert into person_hobby (hobbies_name, persons_id) values ('running', 426);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 427);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 428);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 429);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 430);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 431);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 432);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 433);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 434);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 435);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 436);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 437);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 438);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 439);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 440);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 441);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 442);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 443);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 444);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 445);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 446);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 447);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 448);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 449);
insert into person_hobby (hobbies_name, persons_id) values ('running', 450);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 451);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 452);
insert into person_hobby (hobbies_name, persons_id) values ('running', 453);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 454);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 455);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 456);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 457);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 458);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 459);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 460);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 461);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 462);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 463);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 464);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 465);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 466);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 467);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 468);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 469);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 470);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 471);
insert into person_hobby (hobbies_name, persons_id) values ('running', 472);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 473);
insert into person_hobby (hobbies_name, persons_id) values ('running', 474);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 475);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 476);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 477);
insert into person_hobby (hobbies_name, persons_id) values ('running', 478);
insert into person_hobby (hobbies_name, persons_id) values ('running', 479);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 480);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 481);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 482);
insert into person_hobby (hobbies_name, persons_id) values ('running', 483);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 484);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 485);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 486);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 487);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 488);
insert into person_hobby (hobbies_name, persons_id) values ('running', 489);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 490);
insert into person_hobby (hobbies_name, persons_id) values ('running', 491);
insert into person_hobby (hobbies_name, persons_id) values ('running', 492);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 493);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 494);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 495);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 496);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 497);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 498);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 499);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 500);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 501);
insert into person_hobby (hobbies_name, persons_id) values ('running', 502);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 503);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 504);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 505);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 506);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 507);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 508);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 509);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 510);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 511);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 512);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 513);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 514);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 515);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 516);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 517);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 518);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 519);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 520);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 521);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 522);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 523);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 524);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 525);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 526);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 527);
insert into person_hobby (hobbies_name, persons_id) values ('running', 528);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 529);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 530);
insert into person_hobby (hobbies_name, persons_id) values ('running', 531);
insert into person_hobby (hobbies_name, persons_id) values ('running', 532);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 533);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 534);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 535);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 536);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 537);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 538);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 539);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 540);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 541);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 542);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 543);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 544);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 545);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 546);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 547);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 548);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 549);
insert into person_hobby (hobbies_name, persons_id) values ('running', 550);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 551);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 552);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 553);
insert into person_hobby (hobbies_name, persons_id) values ('running', 554);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 555);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 556);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 557);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 558);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 559);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 560);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 561);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 562);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 563);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 564);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 565);
insert into person_hobby (hobbies_name, persons_id) values ('running', 566);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 567);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 568);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 569);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 570);
insert into person_hobby (hobbies_name, persons_id) values ('running', 571);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 572);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 573);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 574);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 575);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 576);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 577);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 578);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 579);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 580);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 581);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 582);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 583);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 584);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 585);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 586);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 587);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 588);
insert into person_hobby (hobbies_name, persons_id) values ('running', 589);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 590);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 591);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 592);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 593);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 594);
insert into person_hobby (hobbies_name, persons_id) values ('running', 595);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 596);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 597);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 598);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 599);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 600);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 601);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 602);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 603);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 604);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 605);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 606);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 607);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 608);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 609);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 610);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 611);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 612);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 613);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 614);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 615);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 616);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 617);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 618);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 619);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 620);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 621);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 622);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 623);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 624);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 625);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 626);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 627);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 628);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 629);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 630);
insert into person_hobby (hobbies_name, persons_id) values ('running', 631);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 632);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 633);
insert into person_hobby (hobbies_name, persons_id) values ('running', 634);
insert into person_hobby (hobbies_name, persons_id) values ('running', 635);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 636);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 637);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 638);
insert into person_hobby (hobbies_name, persons_id) values ('running', 639);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 640);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 641);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 642);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 643);
insert into person_hobby (hobbies_name, persons_id) values ('running', 644);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 645);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 646);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 647);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 648);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 649);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 650);
insert into person_hobby (hobbies_name, persons_id) values ('running', 651);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 652);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 653);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 654);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 655);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 656);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 657);
insert into person_hobby (hobbies_name, persons_id) values ('running', 658);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 659);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 660);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 661);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 662);
insert into person_hobby (hobbies_name, persons_id) values ('running', 663);
insert into person_hobby (hobbies_name, persons_id) values ('running', 664);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 665);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 666);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 667);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 668);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 669);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 670);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 671);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 672);
insert into person_hobby (hobbies_name, persons_id) values ('running', 673);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 674);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 675);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 676);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 677);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 678);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 679);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 680);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 681);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 682);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 683);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 684);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 685);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 686);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 687);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 688);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 689);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 690);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 691);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 692);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 693);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 694);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 695);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 696);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 697);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 698);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 699);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 700);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 701);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 702);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 703);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 704);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 705);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 706);
insert into person_hobby (hobbies_name, persons_id) values ('running', 707);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 708);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 709);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 710);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 711);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 712);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 713);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 714);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 715);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 716);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 717);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 718);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 719);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 720);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 721);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 722);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 723);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 724);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 725);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 726);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 727);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 728);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 729);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 730);
insert into person_hobby (hobbies_name, persons_id) values ('running', 731);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 732);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 733);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 734);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 735);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 736);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 737);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 738);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 739);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 740);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 741);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 742);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 743);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 744);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 745);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 746);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 747);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 748);
insert into person_hobby (hobbies_name, persons_id) values ('running', 749);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 750);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 751);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 752);
insert into person_hobby (hobbies_name, persons_id) values ('running', 753);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 754);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 755);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 756);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 757);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 758);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 759);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 760);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 761);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 762);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 763);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 764);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 765);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 766);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 767);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 768);
insert into person_hobby (hobbies_name, persons_id) values ('running', 769);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 770);
insert into person_hobby (hobbies_name, persons_id) values ('running', 771);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 772);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 773);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 774);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 775);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 776);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 777);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 778);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 779);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 780);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 781);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 782);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 783);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 784);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 785);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 786);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 787);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 788);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 789);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 790);
insert into person_hobby (hobbies_name, persons_id) values ('running', 791);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 792);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 793);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 794);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 795);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 796);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 797);
insert into person_hobby (hobbies_name, persons_id) values ('running', 798);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 799);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 800);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 801);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 802);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 803);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 804);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 805);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 806);
insert into person_hobby (hobbies_name, persons_id) values ('running', 807);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 808);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 809);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 810);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 811);
insert into person_hobby (hobbies_name, persons_id) values ('running', 812);
insert into person_hobby (hobbies_name, persons_id) values ('running', 813);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 814);
insert into person_hobby (hobbies_name, persons_id) values ('running', 815);
insert into person_hobby (hobbies_name, persons_id) values ('running', 816);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 817);
insert into person_hobby (hobbies_name, persons_id) values ('running', 818);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 819);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 820);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 821);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 822);
insert into person_hobby (hobbies_name, persons_id) values ('running', 823);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 824);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 825);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 826);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 827);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 828);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 829);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 830);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 831);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 832);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 833);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 834);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 835);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 836);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 837);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 838);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 839);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 840);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 841);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 842);
insert into person_hobby (hobbies_name, persons_id) values ('running', 843);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 844);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 845);
insert into person_hobby (hobbies_name, persons_id) values ('running', 846);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 847);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 848);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 849);
insert into person_hobby (hobbies_name, persons_id) values ('running', 850);
insert into person_hobby (hobbies_name, persons_id) values ('running', 851);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 852);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 853);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 854);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 855);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 856);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 857);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 858);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 859);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 860);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 861);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 862);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 863);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 864);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 865);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 866);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 867);
insert into person_hobby (hobbies_name, persons_id) values ('running', 868);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 869);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 870);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 871);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 872);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 873);
insert into person_hobby (hobbies_name, persons_id) values ('running', 874);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 875);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 876);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 877);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 878);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 879);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 880);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 881);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 882);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 883);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 884);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 885);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 886);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 887);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 888);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 889);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 890);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 891);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 892);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 893);
insert into person_hobby (hobbies_name, persons_id) values ('running', 894);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 895);
insert into person_hobby (hobbies_name, persons_id) values ('running', 896);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 897);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 898);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 899);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 900);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 901);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 902);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 903);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 904);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 905);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 906);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 907);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 908);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 909);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 910);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 911);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 912);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 913);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 914);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 915);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 916);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 917);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 918);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 919);
insert into person_hobby (hobbies_name, persons_id) values ('running', 920);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 921);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 922);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 923);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 924);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 925);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 926);
insert into person_hobby (hobbies_name, persons_id) values ('running', 927);
insert into person_hobby (hobbies_name, persons_id) values ('running', 928);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 929);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 930);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 931);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 932);
insert into person_hobby (hobbies_name, persons_id) values ('running', 933);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 934);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 935);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 936);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 937);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 938);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 939);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 940);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 941);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 942);
insert into person_hobby (hobbies_name, persons_id) values ('running', 943);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 944);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 945);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 946);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 947);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 948);
insert into person_hobby (hobbies_name, persons_id) values ('running', 949);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 950);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 951);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 952);
insert into person_hobby (hobbies_name, persons_id) values ('running', 953);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 954);
insert into person_hobby (hobbies_name, persons_id) values ('running', 955);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 956);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 957);
insert into person_hobby (hobbies_name, persons_id) values ('running', 958);
insert into person_hobby (hobbies_name, persons_id) values ('running', 959);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 960);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 961);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 962);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 963);
insert into person_hobby (hobbies_name, persons_id) values ('running', 964);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 965);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 966);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 967);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 968);
insert into person_hobby (hobbies_name, persons_id) values ('running', 969);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 970);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 971);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 972);
insert into person_hobby (hobbies_name, persons_id) values ('freediving', 973);
insert into person_hobby (hobbies_name, persons_id) values ('running', 974);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 975);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 976);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 977);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 978);
insert into person_hobby (hobbies_name, persons_id) values ('jumping', 979);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 980);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 981);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 982);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 983);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 984);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 985);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 986);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 987);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 988);
insert into person_hobby (hobbies_name, persons_id) values ('chess', 989);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 990);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 991);
insert into person_hobby (hobbies_name, persons_id) values ('running', 992);
insert into person_hobby (hobbies_name, persons_id) values ('swimming', 993);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 994);
insert into person_hobby (hobbies_name, persons_id) values ('running', 995);
insert into person_hobby (hobbies_name, persons_id) values ('gaming', 996);
insert into person_hobby (hobbies_name, persons_id) values ('programming', 997);
insert into person_hobby (hobbies_name, persons_id) values ('magic cards', 998);
insert into person_hobby (hobbies_name, persons_id) values ('scubadiving', 999);
insert into person_hobby (hobbies_name, persons_id) values ('grand theft auto', 1000);
