insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 1);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 2);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 3);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 4);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 5);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 6);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 7);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 8);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 9);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 10);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 11);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 12);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 13);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 14);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 15);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 16);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 17);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 18);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 19);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 20);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 21);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 22);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 23);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 24);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 25);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 26);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 27);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 28);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 29);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 30);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 31);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 32);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 33);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 34);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 35);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 36);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 37);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 38);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 39);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 40);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 41);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 42);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 43);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 44);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 45);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 46);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 47);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 48);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 49);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 50);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 51);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 52);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 53);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 54);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 55);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 56);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 57);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 58);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 59);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 60);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 61);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 62);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 63);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 64);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 65);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 66);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 67);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 68);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 69);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 70);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 71);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 72);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 73);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 74);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 75);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 76);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 77);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 78);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 79);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 80);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 81);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 82);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 83);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 84);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 85);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 86);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 87);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 88);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 89);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 90);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 91);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 92);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 93);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 94);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 95);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 96);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 97);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 98);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 99);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 100);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 101);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 102);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 103);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 104);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 105);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 106);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 107);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 108);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 109);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 110);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 111);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 112);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 113);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 114);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 115);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 116);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 117);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 118);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 119);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 120);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 121);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 122);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 123);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 124);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 125);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 126);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 127);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 128);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 129);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 130);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 131);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 132);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 133);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 134);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 135);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 136);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 137);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 138);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 139);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 140);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 141);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 142);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 143);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 144);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 145);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 146);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 147);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 148);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 149);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 150);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 151);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 152);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 153);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 154);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 155);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 156);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 157);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 158);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 159);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 160);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 161);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 162);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 163);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 164);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 165);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 166);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 167);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 168);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 169);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 170);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 171);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 172);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 173);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 174);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 175);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 176);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 177);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 178);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 179);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 180);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 181);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 182);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 183);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 184);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 185);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 186);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 187);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 188);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 189);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 190);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 191);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 192);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 193);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 194);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 195);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 196);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 197);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 198);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 199);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 200);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 201);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 202);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 203);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 204);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 205);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 206);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 207);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 208);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 209);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 210);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 211);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 212);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 213);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 214);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 215);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 216);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 217);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 218);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 219);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 220);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 221);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 222);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 223);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 224);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 225);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 226);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 227);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 228);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 229);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 230);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 231);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 232);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 233);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 234);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 235);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 236);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 237);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 238);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 239);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 240);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 241);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 242);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 243);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 244);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 245);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 246);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 247);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 248);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 249);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 250);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 251);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 252);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 253);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 254);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 255);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 256);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 257);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 258);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 259);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 260);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 261);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 262);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 263);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 264);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 265);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 266);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 267);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 268);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 269);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 270);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 271);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 272);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 273);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 274);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 275);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 276);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 277);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 278);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 279);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 280);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 281);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 282);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 283);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 284);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 285);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 286);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 287);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 288);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 289);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 290);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 291);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 292);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 293);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 294);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 295);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 296);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 297);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 298);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 299);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 300);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 301);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 302);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 303);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 304);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 305);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 306);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 307);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 308);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 309);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 310);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 311);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 312);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 313);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 314);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 315);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 316);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 317);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 318);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 319);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 320);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 321);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 322);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 323);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 324);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 325);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 326);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 327);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 328);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 329);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 330);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 331);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 332);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 333);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 334);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 335);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 336);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 337);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 338);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 339);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 340);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 341);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 342);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 343);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 344);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 345);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 346);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 347);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 348);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 349);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 350);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 351);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 352);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 353);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 354);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 355);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 356);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 357);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 358);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 359);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 360);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 361);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 362);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 363);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 364);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 365);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 366);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 367);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 368);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 369);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 370);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 371);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 372);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 373);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 374);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 375);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 376);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 377);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 378);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 379);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 380);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 381);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 382);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 383);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 384);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 385);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 386);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 387);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 388);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 389);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 390);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 391);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 392);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 393);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 394);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 395);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 396);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 397);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 398);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 399);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 400);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 401);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 402);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 403);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 404);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 405);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 406);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 407);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 408);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 409);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 410);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 411);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 412);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 413);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 414);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 415);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 416);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 417);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 418);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 419);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 420);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 421);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 422);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 423);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 424);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 425);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 426);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 427);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 428);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 429);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 430);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 431);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 432);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 433);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 434);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 435);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 436);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 437);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 438);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 439);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 440);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 441);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 442);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 443);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 444);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 445);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 446);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 447);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 448);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 449);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 450);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 451);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 452);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 453);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 454);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 455);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 456);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 457);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 458);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 459);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 460);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 461);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 462);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 463);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 464);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 465);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 466);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 467);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 468);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 469);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 470);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 471);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 472);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 473);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 474);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 475);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 476);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 477);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 478);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 479);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 480);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 481);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 482);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 483);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 484);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 485);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 486);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 487);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 488);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 489);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 490);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 491);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 492);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 493);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 494);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 495);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 496);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 497);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 498);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 499);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 500);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 501);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 502);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 503);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 504);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 505);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 506);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 507);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 508);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 509);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 510);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 511);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 512);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 513);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 514);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 515);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 516);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 517);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 518);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 519);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 520);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 521);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 522);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 523);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 524);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 525);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 526);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 527);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 528);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 529);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 530);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 531);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 532);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 533);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 534);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 535);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 536);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 537);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 538);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 539);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 540);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 541);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 542);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 543);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 544);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 545);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 546);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 547);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 548);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 549);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 550);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 551);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 552);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 553);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 554);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 555);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 556);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 557);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 558);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 559);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 560);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 561);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 562);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 563);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 564);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 565);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 566);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 567);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 568);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 569);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 570);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 571);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 572);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 573);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 574);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 575);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 576);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 577);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 578);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 579);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 580);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 581);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 582);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 583);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 584);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 585);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 586);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 587);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 588);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 589);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 590);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 591);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 592);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 593);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 594);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 595);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 596);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 597);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 598);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 599);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 600);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 601);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 602);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 603);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 604);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 605);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 606);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 607);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 608);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 609);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 610);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 611);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 612);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 613);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 614);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 615);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 616);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 617);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 618);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 619);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 620);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 621);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 622);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 623);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 624);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 625);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 626);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 627);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 628);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 629);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 630);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 631);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 632);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 633);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 634);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 635);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 636);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 637);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 638);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 639);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 640);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 641);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 642);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 643);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 644);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 645);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 646);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 647);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 648);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 649);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 650);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 651);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 652);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 653);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 654);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 655);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 656);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 657);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 658);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 659);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 660);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 661);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 662);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 663);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 664);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 665);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 666);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 667);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 668);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 669);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 670);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 671);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 672);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 673);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 674);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 675);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 676);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 677);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 678);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 679);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 680);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 681);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 682);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 683);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 684);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 685);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 686);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 687);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 688);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 689);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 690);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 691);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 692);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 693);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 694);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 695);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 696);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 697);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 698);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 699);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 700);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 701);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 702);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 703);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 704);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 705);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 706);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 707);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 708);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 709);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 710);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 711);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 712);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 713);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 714);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 715);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 716);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 717);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 718);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 719);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 720);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 721);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 722);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 723);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 724);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 725);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 726);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 727);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 728);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 729);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 730);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 731);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 732);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 733);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 734);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 735);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 736);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 737);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 738);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 739);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 740);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 741);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 742);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 743);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 744);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 745);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 746);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 747);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 748);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 749);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 750);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 751);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 752);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 753);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 754);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 755);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 756);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 757);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 758);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 759);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 760);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 761);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 762);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 763);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 764);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 765);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 766);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 767);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 768);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 769);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 770);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 771);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 772);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 773);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 774);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 775);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 776);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 777);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 778);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 779);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 780);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 781);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 782);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 783);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 784);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 785);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 786);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 787);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 788);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 789);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 790);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 791);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 792);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 793);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 794);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 795);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 796);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 797);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 798);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 799);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 800);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 801);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 802);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 803);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 804);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 805);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 806);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 807);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 808);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 809);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 810);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 811);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 812);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 813);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 814);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 815);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 816);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 817);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 818);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 819);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 820);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 821);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 822);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 823);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 824);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 825);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 826);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 827);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 828);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 829);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 830);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 831);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 832);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 833);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 834);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 835);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 836);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 837);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 838);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 839);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 840);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 841);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 842);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 843);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 844);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 845);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 846);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 847);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 848);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 849);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 850);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 851);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 852);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 853);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 854);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 855);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 856);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 857);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 858);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 859);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 860);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 861);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 862);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 863);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 864);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 865);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 866);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 867);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 868);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 869);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 870);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 871);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 872);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 873);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 874);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 875);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 876);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 877);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 878);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 879);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 880);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 881);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 882);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 883);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 884);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 885);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 886);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 887);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 888);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 889);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 890);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 891);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 892);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 893);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 894);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 895);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 896);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 897);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 898);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 899);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 900);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 901);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 902);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 903);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 904);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 905);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 906);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 907);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 908);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 909);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 910);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 911);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 912);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 913);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 914);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 915);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 916);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 917);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 918);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 919);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 920);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 921);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 922);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 923);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 924);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 925);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 926);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 927);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 928);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 929);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 930);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 931);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 932);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 933);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 934);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 935);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 936);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 937);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 938);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 939);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 940);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 941);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 942);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 943);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 944);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 945);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 946);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 947);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 948);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 949);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 950);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 951);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 952);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 953);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 954);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 955);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 956);
insert into person_hobby (hobbies_name, persons_id) values ('cycling', 957);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 958);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 959);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 960);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 961);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 962);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 963);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 964);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 965);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 966);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 967);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 968);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 969);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 970);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 971);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 972);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 973);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 974);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 975);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 976);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 977);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 978);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 979);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 980);
insert into person_hobby (hobbies_name, persons_id) values ('sketching', 981);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 982);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 983);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 984);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 985);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 986);
insert into person_hobby (hobbies_name, persons_id) values ('shooting', 987);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 988);
insert into person_hobby (hobbies_name, persons_id) values ('soapmaking', 989);
insert into person_hobby (hobbies_name, persons_id) values ('skydiving', 990);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 991);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 992);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 993);
insert into person_hobby (hobbies_name, persons_id) values ('fishing', 994);
insert into person_hobby (hobbies_name, persons_id) values ('archery', 995);
insert into person_hobby (hobbies_name, persons_id) values ('dance', 996);
insert into person_hobby (hobbies_name, persons_id) values ('stand-up comedy', 997);
insert into person_hobby (hobbies_name, persons_id) values ('yoga', 998);
insert into person_hobby (hobbies_name, persons_id) values ('coffee roasting', 999);
insert into person_hobby (hobbies_name, persons_id) values ('sewing', 1000);
